### ISSUE TITLE
Manually Added Products searching results

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/StockUp#412]
When "Add Products Manually" is used to create an order, the results from the search are incomplete and inaccurate, more or less. Example: Seaching for SKU 100 returns 10 results where SKUs have some form of 100 in them but not the SKU that equals exactly 100. This searching functionality should return exact match(es) first then the remainder which would include the search term. In my SQL world it would be select * where SKU=="100" or SKU=*100* which would return 
100 - Greeting Cards
51005 - SHUNGA DESENSITIZING SPRAY
62100 - BFF G-SPOT MSSGR PINK SLCN
2010010 - GARTER ASST
2010091 - GARTER BELT QS ASST
etc.
etc.
![SU - Search results problem example](https://user-images.githubusercontent.com/10925748/74559189-6bdb2980-4f29-11ea-8c43-89266726d291.png)

**Comment by kamal0808** [comment]
Gotcha, will work on it

**Comment by kamal0808** [comment]
Closed by mistake. Reopened until fix is tested and confirmed

**Comment by elbrando** [comment]
Tested the scenario above and 100 was top result. Was a fix deployed? I'll do some further testing and we can close this issue if so.

**Comment by kamal0808** [comment]
@with-shrey test this and close

**Comment by with-shrey** [comment]
working fine
