### ISSUE TITLE
Error displaying reorder points calculation for file imported orders

### ISSUE THREAD

**Issue by khushbupathe** [ShoppinPal/StockUp#414]
![image](https://user-images.githubusercontent.com/26260591/74627598-6aa03b80-5179-11ea-9175-c0f6eba47b31.png)

**Comment by kamal0808** [comment]
Possible solution: Track file imports in ReportModel, and display the suggested quantity reason accordingly in all file imported orders.
Thanks @khushbupathe for testing this.
