### ISSUE TITLE
Create alphabetical category anchors for generated orders

### ISSUE THREAD

**Issue by kamal0808** [ShoppinPal/StockUp#415]
So that users can directly scroll down to specific category of items in the order.
For example, an order containing items of category "Electronics", "Gifts", etc. , there should be anchors like "E","G" that when clicked on takes users to "Electronics", "Gifts" respectively.

**Comment by with-shrey** [comment]
UI: https://slack-files.com/T0TM5STB3-F0110C9QYTW-80773c9086
