### ISSUE TITLE
#2 Discrepancy report

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/StockUp#416]
(Might need to be tied to feature development. More info at bottom)

For items not received in the same qty on the receiving order, a report showing which items and which quantities, separated/sorted by what kind (too many, too few, none), which can be emailed [CSV/PDF is fine @elbrando to confirm preference], exported [CSV], and archived [searchable and available forever]. The data should also be "reportable", i.e. filterable by date, supplier, outlet, groupable, etc. via a Reporting section.

**addendum** We had a feature designed long ago where the managers are able to mark products on the generated order as either Shoplifted or Damaged in Store. I need to do more discovery on this but the basics are having something like a radio button in the dropdown details portion of the product's line display with "Shoplifted" "Damaged" and possibly another option. *Needs to be dead simple UX wise* -- loop in Anshul for this. This info needs to be "reportable" just like the discrepancies above. These features are very similar with similar reporting requirements which is why I suggested they may need to be tied together.

I'll get mockups of these concepts ASAP.

**Comment by elbrando** [comment]
Quick note: Damaged in Store means items that the store has previously received to completion and are somehow no longer sellable due to sun damage, dropped, or whatever. These damaged goods are handled differently, accounting wise. See #417 for Damaged in Shipping.

**Comment by srisub** [comment]
Yash - need to review data architecture to ensure reporting needs (this one and others) can be supported and scaled.

**Comment by srisub** [comment]
Use case: Run a report for Jan in OKC stores, be able to see that 1 of the stores had a 20% increase in shoplifting...this will help spot issues early on and triage further.

**Comment by kamal0808** [comment]
Question @elbrando : - How is shoplifted or damaged items handled in next generated order? Need to discuss over meeting.

**Comment by kamal0808** [comment]
<img width="747" alt="Screenshot 2021-02-26 at 8 44 32 PM" src="https://user-images.githubusercontent.com/15616412/109318295-a9300200-7873-11eb-8469-d82fe21b9de7.png">

**Comment by kamal0808** [comment]
2 separate panels in User Management details for different roles of selected stores:
- Manage generation/fulfilling/receivals
- Manage discrepancies
-
<img width="654" alt="Screenshot 2021-02-26 at 9 28 05 PM" src="https://user-images.githubusercontent.com/15616412/109323587-a33d1f80-7879-11eb-859c-40453b2a7f02.png">
<img width="745" alt="Screenshot 2021-02-26 at 9 28 34 PM" src="https://user-images.githubusercontent.com/15616412/109323599-a59f7980-7879-11eb-8bbb-fa9cc86f05d9.png">
