### ISSUE TITLE
#1 Improve order's Items tabs

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/StockUp#426]
1) Instead of Not Approved/Approved for Generated orders, first tab should be "Needs review", second should be "Approved" then third should be "Do Not Want" (or somesuch). Not Approved, in this case is an action saying, "No, I don't want this" instead of the current "hasn't been looked at yet" combined with "I don't want this". The differentiation is important for inventory management. This would require an additional input available for users to mark the item as Do Not Want, which should be in the add'l info/input section of line items. Maybe just above the Send (comment) button? I'm happy to discuss further if you guys have suggestion or better options.

2) Similar for Receiving but with even an extra tab - First tab: "Needs review" Second tab: "Received" Third tab: "Back Ordered" (ideally, all Fulfilled Qty = 0 items automatically are in this section as part of import) Fourth tab: "Discrepancies" (this is where anything with Received Quantity<>Ordered Quantity, included manually added or removed items, would move to). Whatever was in Received Quantity still needs to be received, however. This would also require additional input from users. 

There's still some thinking out on this to be done but this is mostly there.

**Comment by kamal0808** [comment]
@elbrando if in a case of an item:  10 ordered, 5 delivered, 3 received => Should it go to backordered or discrepancy or BOTH?

**Comment by kamal0808** [comment]
Discussion over this issue:

Backorder items will be filtered out by items in the sheet that have ZERO(0) in the Fulfilled columns.

**Another Issue**: File imports should be linked to generated orders, to update an existing order.

- Discrepancy and a stock return are 2 separate things.
- For item quantities delivered more than what was said to be delivered, then a popup appears.
- For item quantities delivered less than what is said to be delivered, then at the end of scanning activity, the discrepancy tab fills up.

**Comment by elbrando** [comment]
![receivings tabs tweak](https://user-images.githubusercontent.com/10925748/109309966-94b71f80-7809-11eb-81cf-1642d83b0bba.png)
![generating tabs tweaks](https://user-images.githubusercontent.com/10925748/109309968-954fb600-7809-11eb-94fa-8d0bbf9d8508.png)

**Comment by kamal0808** [comment]
- Split approve button into two: a) Approve (green tick check mark) b) Reject (red cross mark)
No need for text in the buttons, just the icons would suffice to make up for the space @with-shrey

**Comment by with-shrey** [comment]
@elbrando 
Will `Ordered: 5` and `Delivered: 3` show in backorder tab as `backordered: 2`?

**Comment by elbrando** [comment]
> @elbrando
> Will `Ordered: 5` and `Delivered: 3` show in backorder tab as `backordered: 2`?

Yes, that's correct.
