### ISSUE TITLE
Error sending to Supplier

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/StockUp#436]
71st's order errored when sending again this week. It happened last week but I figured it was a fluke but it happened again. I tried to resend it once then tried to export it. I got the error that I screenshotted and attached here, if it's of any help.

I'll need to get this to the warehouse ASAP so let me know as soon as it is fixed.

Thanks,
Brandon
![error exporting stockup order](https://user-images.githubusercontent.com/10925748/83450742-75769780-a41b-11ea-891f-93ad7179d45c.png)

**Comment by khushbupathe** [comment]
Hey @elbrando The above issue is now fixed and tested. You can find an evidence link [here](https://drive.google.com/file/d/1NJdAykCgDBRs-JNP0Mfo_yUFHgAawzWN/view?usp=sharing).

**Comment by kamal0808** [comment]
@elbrando the submission failed in the first place due to Vend outage. Let us know if the issue persists today.

**Comment by elbrando** [comment]
If the error exporting was due to the outage and it was fixed, great. But I'm still getting an error when I try to submit it to supplier.

**Comment by kamal0808** [comment]
@elbrando Can you please try again?

**Comment by kamal0808** [comment]
Solved manually. Created #437 to track the issue further.
