### ISSUE TITLE
Fulfill All button

### ISSUE THREAD

**Issue by elbrando** [ShoppinPal/StockUp#488]
I am currently having to fulfill all of our LCD orders manually so that our staff can receive them in StockUp, instead of Vend. Receiving in StockUp is certainly preferable and since the LCD fulfillment process won't be using StockUp for the foreseeable future, I will be having to do this for some time.

Could we add a "Fulfill All" button so that process doesn't suck the life out of me? I don't mind fulfilling each order manually, just not each item manually. Ideally, this is tied to a Role so the normal fulfiller wouldn't have access.

If this is quick and easy, I'd like at the top of the list.

**Comment by with-shrey** [comment]
@elbrando The Fulfill All Button will fulfill all the items in the order and set the fulfill-quantity same as order-quantity ?

**Comment by elbrando** [comment]
Yes, that is correct @with-shrey. We have to do it that way because the LCD warehouse does not use StockUp (but hopefully will someday) and does not provide an import file or any data on the orders except the paper packing list/picking ticket in the box. *sigh*

We should have a chat and I'll fill you in on the particulars of our company, if you don't know about it already.

**Comment by elbrando** [comment]
This is also where Discrepancy data and reporting as well as BackOrder stuff will be super useful.
